# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 876a26011f399ceb5264592a079ffa0883ef98fc894b2fe356257bfeb1d6dd0b810ac09c21ae20b42914128cf8d201a49b82a5894e7ff9ca52297e91ded4a7f0

test:
  secret_key_base: b7873a2b44f8826c82ddec6473fd5dee7a368832991d13acc655fd4bff0b81977e20eaff056ed85eaa861bf552649d5124edb901bc0d9c2862ec534fc0a1323b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 829e4be4bbec6994e0fb448432480ab6569e463dd8de86aa664e50a7912af32471b97fe4706db9aca188f747a1463309b901d4bb3b7a1229da80bd070efc7bd2
